#!/bin/bash
# sysinfo_page - A script to produce an HTML file

title="System of"
right_now=$(date +"%A,%Y")
TIME_STAMP="update on $right_now by $USER"
test=$title




system_uptime(){
echo "<h2>System Uptime</h2>"
echo "<pre>"
  uptime
echo "</pre>"

}




cat <<- EOF_FILE
 <html>
 <head>
   <title>
   $title $HOSTNAME 
   </title>
 </head>
 
 <body>
   $title $HOSTNAME 
   <p>$TIME_STAMP</p>
   <p>update on `date +"%A,%Y"` by $USER</p>
   $(system_uptime)
   $test
 </body>
 </html>
EOF_FILE
