#!/bin/bash -x
number=10

#if statement
#--------------------------------
#test expression format 1
if test $number=10 ;then
echo number is equal to 10
fi

#test expression format 2
if [ $number=10 ]; then
echo number is equal to 10
fi

#if else statement
#--------------------------
number=11
if [ $number = 10 ]; then
echo number is equal to 10
else 
echo number is not equal to 10
fi

#if elif else
#--------------------------------
number=10
if [ $number -lt 10 ];then
echo number <10
elif [ $number -gt 10 ];then
echo number>10
else
echo number==10
fi
