#!/bin/bash
year=`date +%y`
month=`date +%m`
day=`date +%d`
hour=`date +%h`

hours=`date +%H`
minutes=`date +%M`
seconds=`date +%S`

echo year=$year month=$month day=$day
echo hours=$hours minutes=$minutes seconds=$seconds
