#!/bin/bash -x
for line in "$(cat file)";do
array=(${array[*]} $line)
 done

count=0
for ele in ${array[*]};do

 if [[ $ele == [A-Z] ]];then

    prev=$id
    id=$ele

    if [[ $prev != "" && $count -lt 3 ]];then
    
       echo $prev $count
    fi
     
   count=0

 fi
 if [[ $ele != [A-Z] && $ele -ge 0 && $ele -le 100 ]];then
   ((count++))
 fi
 
 done

