#!/bin/bash


factorial(){

if [ $1 -le 1 ];then 
   echo 1
   return 0
fi

nextNum=$(($1 - 1))
nextfactorial=$(factorial $nextNum) 
result=$(( $nextfactorial * $1 ))

echo $result
return 0
}

echo "Enter Number to find its factorial" 
read num

fact=$(factorial $num)
echo factorial of $num is =$fact

