#!/bin/bash -x
echo "enter two numbers"

read num1
read num2


getHCF(){
if [ $1 = 0 ];then
echo $2

else 
if [ $1 -lt $2 ];then
   rem=$(($2 % $1)) 
  getHCF $rem $1
else
   rem=$(($1 % $2))
   getHCF $rem $2 
fi
fi
}



getHCF $num1 $num2
