#!/bin/bash

method(){
# num1,num2 arguments passed to method as $1,$2 like commandline
 
 echo first parameter=$1
 echo second parameter=$2
 
}
 
echo "enter num 1" 
read num1
echo "enter num 2"
read num2


method $num1 $num2
